### ISSUE TITLE
Not working for j5nlte

### ISSUE THREAD

**Issue by FaserF** [daviiid99/Galaxy_J5_Updater#1]
Stuck at searching for updates.

```
pygame 2.1.2 (SDL 2.0.18, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-1 (download_latest_json):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "check.py", line 81, in download_latest_json
FileNotFoundError: [Errno 2] No such file or directory: 'j5nlte.json'
```

**Comment by damolmo** [comment]
Are you trying to update from one of my supported OS (11,12 or 13)?

If you try to update from recovery the program will not find the supported version and will fail to download the file

**Comment by FaserF** [comment]
ahhh okay thanks. Then of course it could not work. Maybe another information on the start screen would be helpful about this :)

**Comment by daxnv** [comment]
Sorry for bumping this thread, I've got the same issue. So what do I have to have installed on my phone? Didn't understand that one.
