### ISSUE TITLE
Which J5?

### ISSUE THREAD

**Issue by jason-eu** [daviiid99/Galaxy_J5_Updater#2]
I have a Samsung Galaxy J530F, and I'm not sure if it's compatible with your updater.

Where can I find more information on supported models?

**Comment by leopold-heusel** [comment]
According to [this article](https://forum.xda-developers.com/t/rom-12l-unofficial-gapps-ota-lineageos-19-1-for-galaxy-j5-unified-2022-08-11.4416375/) by the author: SM-J500FN, SM-J500F/G/M/NO/Y, SM-J5008, SM-J500H
